# Generated by Django 4.1.6 on 2023-02-06 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('provider', 'Provider')], default='customer', max_length=8)),
                ('name', models.CharField(max_length=240)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('registry_nr', models.CharField(max_length=50)),
                ('vat_nr', models.CharField(blank=True, max_length=50)),
                ('iban', models.CharField(blank=True, max_length=50, verbose_name='IBAN')),
                ('bic_swift', models.CharField(blank=True, max_length=50, verbose_name='BIC/SWIFT')),
            ],
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_nr', models.CharField(max_length=20)),
                ('created', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='customer', to='api.company')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='provider', to='api.company')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('amount', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_bodies', to='api.invoice')),
            ],
            options={
                'verbose_name': 'invoice body',
                'verbose_name_plural': 'invoice bodies',
            },
        ),
    ]
