# Generated by Django 4.1.6 on 2023-02-06 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('amount', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_rows', to='api.invoice')),
            ],
            options={
                'verbose_name': 'invoice row',
                'verbose_name_plural': 'invoice rows',
            },
        ),
        migrations.DeleteModel(
            name='InvoiceBody',
        ),
    ]
