# Generated by Django 4.1.6 on 2023-02-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='bic_swift',
            field=models.CharField(max_length=50, verbose_name='BIC/SWIFT'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='iban',
            field=models.CharField(max_length=50, verbose_name='IBAN'),
        ),
    ]
